project_name: prometheus-libvirt-exporter
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: prometheus-libvirt-exporter
    dir: .
    main: ./main.go
    binary: prometheus-libvirt-exporter
    flags:
      - -v
    ldflags:
      - -w -s
      - -X {{ .ProjectName }}/meta.Version={{ .Env.EXPORTER_VERSION }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

#Configuration for building packages for apk, deb and rpm package managers
nfpms:
  - id: "prometheus-libvirt-exporter"
    package_name: "prometheus-libvirt-exporter"
    file_name_template: prometheus-libvirt-exporter-{{ .Env.EXPORTER_VERSION }}.{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end -}}
    builds:
      - prometheus-libvirt-exporter
    maintainer: "Knalltuete5000"
    description: |
      Prometheus-libvirt-exporter service (host and vm metrics exposed for prometheus, written in Go with pluggable metric collectors)
    homepage: "https://github.com/Knalltuete5000/prometheus-libvirt-exporter"
    license: "MIT License"
    formats:
      - apk
      - deb
      - rpm
    bindir: "/usr/bin"
    priority: optional
    contents:
      - src: debian/prometheus-libvirt-exporter.service
        dst: /etc/systemd/system/prometheus-libvirt-exporter.service

      - src: debian/prometheus-libvirt-exporter.upstart
        dst: /etc/init/prometheus-libvirt-exporter.conf

archives:
  - name_template: "{{ .ProjectName }}_{{ .Env.EXPORTER_VERSION }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: "{{ .ProjectName }}-{{ .Env.EXPORTER_VERSION }}_checksums.txt"
  algorithm: sha256

# Configuration for GitHub Releases
release:
  github:
    owner: Knalltuete5000
    name: prometheus-libvirt-exporter
  draft: true
  replace_existing_draft: true